//REGSITER       ON  | OFF

//Subbas16’       0  | 1
m.program(0, 0);
//Gedekt8’        2  | 3
m.program(0, 2);
//P+I             4  | 5
m.program(0, 4);
//P+II            6  | 7
m.program(0, 6);
//Quintadena 8’   8  | 9
m.program(0, 8);
//Prestant 4’     10 | 11
m.program(0, 10);
//I+II            12 | 13
m.program(0, 12);
//Salicionaal 8’  14 | 15
m.program(0, 14);
//Roerfluit 4’    16 | 17
m.program(0, 16);


